# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
      - master
  paths:
    include:
    - 'Api'

stages:
- stage: Build
  jobs:
  - job: Build
    pool:
      vmImage: windows-2019

    variables:
      buildConfiguration: 'Release'
      projectFilepath: 'Api/Augustus.Api/Augustus.Api.csproj'

    steps:
    - task: DotNetCoreCLI@2
      displayName: 'Build with dotnet'
      inputs:
        command: 'build'
        projects: '$(projectFilepath)'
        configuration: '$(buildConfiguration)'
        arguments: '--output $(Build.ArtifactStagingDirectory)'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish build artifacts'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

- stage: Deploy
  jobs:
  - job: Deploy
    pool:
      vmImage: windows-2019

    steps:
    - task: DownloadBuildArtifacts@1
      displayName: 'Download build artifacts'
      inputs:
        buildType: 'current'
        downloadType: 'single'
        downloadPath: '$(System.ArtifactsDirectory)'
        artifactName: 'drop'

    - task: AzureRmWebAppDeployment@4
      displayName: 'Deploy to Azure'
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'leconfield-software(af4597b8-06f3-421c-b812-b8bf6057a731)'
        appType: 'webApp'
        WebAppName: 'augustus-api'
        VirtualApplication: '/api'
        packageForLinux: '$(System.ArtifactsDirectory)/drop'
        enableCustomDeployment: true
        DeploymentType: 'webDeploy'
        RemoveAdditionalFilesFlag: true
        