# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
      - master
  paths:
    include:
    - 'Client'

variables:
  projectDirectory: 'Client'

stages:
- stage: Build
  jobs:
  - job: Build

    pool:
      vmImage: windows-2019

    steps:
    - task: NodeTool@0
      displayName: 'Install Node.js'
      inputs:
        versionSpec: '14.x'

    - task: Npm@1
      displayName: 'Install Angular CLI'
      inputs:
        command: 'custom'
        customCommand: 'install -g @angular/cli'

    - task: Npm@1
      displayName: 'Run NPM install'
      inputs:
        command: 'install'
        workingDir: $(projectDirectory)

    - task: CmdLine@2
      displayName: 'Build App'
      inputs:
        script: 'ng build --prod'
        workingDirectory: $(projectDirectory)

    - task: PublishBuildArtifacts@1
      displayName: 'Publish build artifacts'
      inputs:
        PathtoPublish: '$(projectDirectory)/dist/augustus'
        ArtifactName: 'drop'
        publishLocation: 'Container'

- stage: Deploy
  jobs:
  - deployment: Deploy

    pool:
      vmImage: windows-2019

    environment: 'Production'

    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadBuildArtifacts@1
            displayName: 'Download build artifacts'
            inputs:
              buildType: 'current'
              downloadType: 'single'
              downloadPath: '$(System.ArtifactsDirectory)'
              artifactName: 'drop'

          - task: AzureRmWebAppDeployment@4
            displayName: 'Deploy to Azure'
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: 'Augustus'
              appType: 'webApp'
              WebAppName: 'augustus-api'
              packageForLinux: '$(System.ArtifactsDirectory)/drop'
              enableCustomDeployment: true
              DeploymentType: 'webDeploy'
              RemoveAdditionalFilesFlag: true
