// <auto-generated />
using System;
using ExpenseTracker.Api.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ExpenseTracker.Api.Infrastructure.Migrations
{
    [DbContext(typeof(ExpenseTrackerContext))]
    [Migration("20220406144537_AddTransactionUserSuppliedDescriptionColumn")]
    partial class AddTransactionUserSuppliedDescriptionColumn
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ExpenseTracker.Api.Models.Transactions.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal?>("CreditAmount")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("DebitAmount")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SubCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("UserSuppliedDescription")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SubCategoryId");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DebitAmount = 4.99m,
                            Description = "Tesco"
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2021, 1, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DebitAmount = 3.29m,
                            Description = "Asda"
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2021, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DebitAmount = 4.99m,
                            Description = "Tesco"
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2021, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DebitAmount = 3.29m,
                            Description = "Asda"
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2021, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DebitAmount = 4.99m,
                            Description = "Tesco"
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateTime(2021, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DebitAmount = 3.29m,
                            Description = "Asda"
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateTime(2021, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DebitAmount = 4.99m,
                            Description = "Tesco"
                        },
                        new
                        {
                            Id = 8,
                            Date = new DateTime(2021, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DebitAmount = 3.29m,
                            Description = "Asda"
                        });
                });

            modelBuilder.Entity("ExpenseTracker.Api.Models.Transactions.TransactionCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("TransactionCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Groceries"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Amazon"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Eat Out"
                        },
                        new
                        {
                            Id = 301,
                            Name = "Restaurant",
                            ParentId = 3
                        },
                        new
                        {
                            Id = 302,
                            Name = "Pub",
                            ParentId = 3
                        },
                        new
                        {
                            Id = 303,
                            Name = "Fast-Food",
                            ParentId = 3
                        });
                });

            modelBuilder.Entity("ExpenseTracker.Api.Models.Transactions.Transaction", b =>
                {
                    b.HasOne("ExpenseTracker.Api.Models.Transactions.TransactionCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ExpenseTracker.Api.Models.Transactions.TransactionCategory", "SubCategory")
                        .WithMany()
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Category");

                    b.Navigation("SubCategory");
                });

            modelBuilder.Entity("ExpenseTracker.Api.Models.Transactions.TransactionCategory", b =>
                {
                    b.HasOne("ExpenseTracker.Api.Models.Transactions.TransactionCategory", null)
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("ExpenseTracker.Api.Models.Transactions.TransactionCategory", b =>
                {
                    b.Navigation("SubCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
